language: python
puthon: 3.8
script: 
  - cd PythonApplication1
  - pytest
  - cd ..
deploy:
  provider: releases
  pi_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    repo: MalyshevKirill/Lab6New
    branch: master
    tags: false
